version: '3'

services:
  nginx:
    image: nginx:1.15.9-alpine
    restart: always
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    ports:
      - 12346:80
    links:
    - keycloak

  postgres:
    image: postgres:9.6.12
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 15432:5432

  keycloak:
    image: jboss/keycloak:4.8.3.Final
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      TZ: Asia/Shanghai
      #JDBC_PARAMS: "ssl=true"  # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
    ports:
      - 12345:8080
    depends_on:
      - postgres
